### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string

### ISSUE THREAD

**Issue by aldarund** [nearform/node-clinic-flame#40]
```clinic flame -- node server.js
To generate the report press: Ctrl + C
fff
bufferAnalysing data
C:\Users\shape\AppData\Roaming\npm\node_modules\clinic\bin.js:327
        if (err) throw err
                 ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.dirname (path.js:651:5)
    at FrameNode.getAppType (C:\Users\shape\AppData\Roaming\npm\node_modules\clinic\node_modules\@nearform\flame\analysis\frame-node.js:175:63)
    at FrameNode.categorise (C:\Users\shape\AppData\Roaming\npm\node_modules\clinic\node_modules\@nearform\flame\analysis\frame-node.js:91:12)
    at tree.walk (C:\Users\shape\AppData\Roaming\npm\node_modules\clinic\node_modules\@nearform\flame\analysis\index.js:29:12)
    at FrameNode.walk (C:\Users\shape\AppData\Roaming\npm\node_modules\clinic\node_modules\@nearform\flame\analysis\frame-node.js:216:5)
    at children.forEach (C:\Users\shape\AppData\Roaming\npm\node_modules\clinic\node_modules\@nearform\flame\analysis\frame-node.js:218:12)
    at Array.forEach (<anonymous>)
    at FrameNode.walk (C:\Users\shape\AppData\Roaming\npm\node_modules\clinic\node_modules\@nearform\flame\analysis\frame-node.js:217:19)
    at children.forEach (C:\Users\shape\AppData\Roaming\npm\node_modules\clinic\node_modules\@nearform\flame\analysis\frame-node.js:218:12) 
```

Node 11 & Win

**Comment by mcollina** [comment]
are you passing in any flags? Which command are you executing?

**Comment by aldarund** [comment]
@mcollina no flags. clinic flame -- node server.js

**Comment by aldarund** [comment]
There was created a 7972.clinic-flame directory.
And if you want i can provide a project that produce this error

**Comment by mcollina** [comment]
Thanks, it would be helpful!

Il giorno mar 20 nov 2018 alle 20:53 Dmitry Molotkov <
notifications@github.com> ha scritto:

**Comment by aldarund** [comment]
https://www.dropbox.com/s/n9p5m08rguljezs/nd.zip?dl=0 here it is
yarn build first
then u can clinic flame & autocanon http://localhost:3000

**Comment by mcollina** [comment]
I cannot reproduce. 

```js
clinic flame --on-port 'autocannon -c 100 /' -- node server
```

Works perfectly here.

Here is what is being generated: https://upload.clinicjs.org/public/45af5a28189fc3216bf64303acfda224bb0203223e1286df17010739f236073f/12320.clinic-flame.html

**Comment by mcollina** [comment]
![image](https://user-images.githubusercontent.com/52195/48917637-234cd180-ee88-11e8-9e9f-3a33f6955f56.png)

**Comment by aldarund** [comment]
@mcollina tried with on-port - all work fine. But if i launch 
clinic flame -- node server
and autocannon -c 100 http://localhost:300/
as two separate command it fails with that error

**Comment by mcollina** [comment]
running `clinic flame -- node server` on one terminal and `autocannon -c 100 http://localhost:3000/` in another works fine for me.

**Comment by aldarund** [comment]
just tried again :) Still same.  Not working via two commands and working via one https://i.imgur.com/JxAuRL2.png

**Comment by aldarund** [comment]
Maybe ctrl+c is a reason and it somehow got args when hitted

**Comment by aldarund** [comment]
No, just happened with one command too twice in row. 
`clinic flame --on-port 'autocannon -c 10 -a 50000 /' -- node server`

**Comment by mcollina** [comment]
I was able to repro using Node 11.2.0.
Node 10 works as expected.

**Comment by mcollina** [comment]
I'm working on a fix, I'll keep you posted.

**Comment by bartvanremortele** [comment]
I keep having this exact same issue on node `v10.15.3`

**Comment by bartvanremortele** [comment]
Ok so I figured out that if I add this to my package.json
`clinic flame -- node dist/app.js`
I get the error in this ticket but if I manually enter this in my terminal I don't get any error at all and it works.

**Comment by fh48** [comment]
I have the same problem as described by @bartvanremortele with wide `v12.16.1`
